services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # Auto-configure all classes in Classes/ directory
  Gmbit\FlipbookConverter\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  # Controllers
  Gmbit\FlipbookConverter\Controller\FlipbookController:
    public: true
    tags: ['controller.service_arguments']

  Gmbit\FlipbookConverter\Controller\BackendController:
    public: true
    tags: ['controller.service_arguments']

  # Services with explicit configuration
  Gmbit\FlipbookConverter\Service\PdfProcessorService:
    public: true

  Gmbit\FlipbookConverter\Service\ConfigurationService:
    public: true

  # Repositories
  Gmbit\FlipbookConverter\Domain\Repository\FlipbookDocumentRepository:
    public: true

  # ViewHelpers
  Gmbit\FlipbookConverter\ViewHelpers\FlipbookViewHelper:
    public: true

  # Preview Renderer
  Gmbit\FlipbookConverter\Preview\FlipbookPreviewRenderer:
    public: true

  # Cache Services
  cache.flipbook_converter:
    class: 'TYPO3\CMS\Core\Cache\Frontend\FrontendInterface'
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['flipbook_converter']